on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      
      - name: Update Container
        id: update-container
        run: sudo apt-get update
      
      - name: Install Dependencies
        id: install-dependencies
        run: sudo apt-get install -y sassc
      
      - name: Build
        id: build
        run: make
        
      - name: Zip repository
        run: zip -r -9 "build-output.zip" .
        
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: build-output.zip
